#! /bin/sh
### BEGIN INIT INFO
# Provides:          mesh-front
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the mesh-front web frontend
### END INIT INFO
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/var/www/mesh-front-py/mesh_front_web.py
NAME=mesh_front_web.py
DISC=mesh-front
USER=mesh-front

PID_FILE=/var/run/$NAME.pid

test -x $DAEMON || exit 0

### main logic ###
case "$1" in
  start)
	echo -n "Starting $DISC: "
	start-stop-daemon --start --quiet --background --chuid $USER:$USER --exec $DAEMON --pidfile $PID_FILE
        echo "$NAME."
        echo $(pidof python $DAEMON) > $PID_FILE
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --quiet --exec $DAEMON --pidfile $PID_FILE
	kill `cat $PID_FILE`
        rm -f $PID_FILE
        echo "$NAME."
        ;;
  restart|reload)
        echo -n "Restarting $DESC: "
        $0 stop
        sleep 1
        $0 start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
